apiVersion: v1
kind: Service
metadata:
  name: codercomserver-lb
  labels:
    app: codercomserver
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: codercomserver
  type: LoadBalancer